Make icons accessible in different format (CJS, ESM, Vue)
funda-frontend/icons pull request #148
Opened 2021-05-12 07:47 UTC by daniarsuprianto

2021-05-17 09:30 UTC, larsdouweschuitema requested changes

2021-05-17 09:30 UTC, larsdouweschuitema commented on package.json
> +    "prepublishOnly": "run-p build:*"
prepare and preublishonly are using the same command + you can use these commands instead of writing out the whole command again in dev, build etc.

2021-05-17 09:30 UTC, larsdouweschuitema commented on scripts/convert.js
> +    icons.flatMap(async (icon) => {
Line 16 + 30 + 46 are the same method with slightly different content. We can reuse the same logic.

2021-05-17 09:30 UTC, larsdouweschuitema commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
We might as well use a library for this instead of creating a utils file with a single method.
Also I believe you are capitalizing just the first letter?

2021-05-20 08:39 UTC, daniarsuprianto commented on scripts/convert.js
> +    icons.flatMap(async (icon) => {
i'll see what i can do

2021-05-20 08:40 UTC, daniarsuprianto commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
yes only first letter.. it's too simple to install and manage a library imo, one line of code already does its job

2021-05-28 09:46 UTC, larsdouweschuitema commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
I still have the opinion we should replace this with lodash. That is most often installed by default in your node_modules and you don't need to add it as a dependency within the latest node versions.

2021-05-28 09:51 UTC, TobbenTM commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
But this library is _so_ nice right now, with *zero* dependencies! Is it really worth it to change that to remove one line?

2021-05-28 10:02 UTC, larsdouweschuitema commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
I think its overkill to create a utils file when we don't have any utils except capitalizing. And we're not really talking about advanced utils here, but about capitalizing something. This can be done with zero depedencies by using a dependency that is installed by default.

2021-05-28 10:03 UTC, TobbenTM commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
But are you sure it's always installed by default? Are you willing to take that risk?

2021-05-28 10:10 UTC, larsdouweschuitema commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
It's purely a personal preference to not have a utils file when you only have a single method and it's basically never going to change.
But it's an "open comment" on purpose instead of "request changes".

2021-05-28 10:32 UTC, bartderijk approved these changes

2021-05-28 11:27 UTC, dine commented on package.json
>      "husky": "^5.0.9",
here on line 15 we won't have `lib/icons.js` file anymore, right?

2021-05-28 11:43 UTC, dine approved these changes

2021-05-28 11:47 UTC, dine commented on scripts/utils.js
> +  capitalize: (string) => string.charAt(0).toUpperCase() + string.slice(1),
@larsdouweschuitema here I still se as if you are requesting changes
<img width="436" alt="Screenshot 2021-05-28 at 13 44 11" src="https://user-images.githubusercontent.com/28925/119979217-eca52400-bfba-11eb-9c8d-b2ecaa0f4b6a.png">

2021-05-28 13:35 UTC, daniarsuprianto commented on package.json
>      "husky": "^5.0.9",
sharp!

2021-06-11 09:45 UTC, larsdouweschuitema submitted a review, later dismissed

2021-06-11 11:12 UTC, larsdouweschuitema approved these changes

2021-06-11 11:19 UTC, merged